// <auto-generated />
namespace DATA_98_DESKTOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderIdInted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderIdInted));
        
        string IMigrationMetadata.Id
        {
            get { return "202309091605295_OrderIdInted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
