// <auto-generated />
namespace DATA_98_DESKTOP_MK2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UmWhatever : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UmWhatever));
        
        string IMigrationMetadata.Id
        {
            get { return "202312031526223_UmWhatever"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
